signal:
  ours: root://eosuser.cern.ch//eos/user/m/mkolosov/Run2_HHTo4B_NTuples/UL2018/DeepJet_FixedWPBTagSF_wTrgMatchFourLdgBJets_29Oct2023_2018_0L/mc/ggHH4b_tree.root
  legacy: root://eosuser.cern.ch//eos/user/m/mkolosov/Run2_HHTo4B_NTuples/Legacy2018/NTuple_Legacy_bbbb_ntuples_ntuplesPA_2018/SKIM_GluGluToHHTo4B_node_cHHH1_TuneCP5_PSWeights_13TeV-powheg-pythia8/GluGluToHHTo4B_node_cHHH1_TuneCP5_PSWeights_13TeV-powheg-pythia8.root

weights:
  ours: [xsecWeight/1000, genWeight]
  legacy: [XS, genWeight]

lumi: 59740

trigger : True