weights : [ xsecWeight / 1000, genWeight, puWeight ]
# weights : [ xsecWeight / 1000, genWeight, puWeight, btagSF_central, trgSF_central ]

signal : 
  - root://eosuser.cern.ch//eos/user/e/ekoenig/Ntuples/NanoHH4b/training/skim_20231020_preUL2018_0L/mc/ggHH4b_tree.root

qcd : 
  - root://eosuser.cern.ch//eos/user/e/ekoenig/Ntuples/NanoHH4b/training/skim_20231020_preUL2018_0L/mc/qcd-benriched_tree.root
  - root://eosuser.cern.ch//eos/user/e/ekoenig/Ntuples/NanoHH4b/training/skim_20231020_preUL2018_0L/mc/qcd-bgenfilter_tree.root

ttbar : 
  - root://eosuser.cern.ch//eos/user/e/ekoenig/Ntuples/NanoHH4b/training/skim_20231020_preUL2018_0L/mc/ttbar-powheg_tree.root
